data = {
    "Physical Height": "物理高度",
    "Physical Width": "物理宽度",
    "Physical Dimensions": "物理尺寸",
    "Width(CM)": "宽度(CM)",
    "Height(CM)": "高度(CM)",
    "Fixed DPI": "固定DPI",
    "Fixed Size": "固定大小",
    "Resolution Sync Mode": "分辨率同步模式",
    "A Series": "A系列",
    "B Series": "B系列",
    "C Series": "C系列",
    "North American Standard": "北美标准",
    "ANSI Standard": "ANSI标准",
    "Architectural Standard": "建筑标准",
    "Letter (21.6x27.9 cm)": "信纸 (21.6x27.9 cm)",
    "Legal (21.6x35.6 cm)": "法律文件 (21.6x35.6 cm)",
    "Legal junior (20.3x12.7 cm)": "小号法律文件 (20.3x12.7 cm)",
    "Ledger (43.2x27.9 cm)": "账单 (43.2x27.9 cm)",
    "Tabloid (27.9x43.2 cm)": "小报纸 (27.9x43.2 cm)",
    "The PPM base unit is not set to inches, the output DPI parameter will not match the actual parameter!": "PPM 基数未设置为英寸单位,输出DPI参数将与实际参数不一至!",
    "Must be reset to inches!": "需重置为英寸单位!",
    "Switch Width Height": "切换宽高",
    "How to handle DPI and physical pixels when modifying output resolution": "修改输出分辨率时如何处理DPI及物理像素",
    "Keep DPI fixed, modify physical dimensions": "固定DPI不变,修改物理尺寸",
    "Keep the physical dimensions unchanged while modifying the DPI": "固定物理尺寸不变,修改DPI",
    "Printing Helper": "打印助手",
    "Set the resolution required for printing more simply": "更轻松地设置打印所需的分辨率",
    "Set the resolution required for printing more simply.": "更轻松地设置打印所需的分辨率.",
    "Out DPI": "输出DPI",
    "Width (CM)": "宽度 (CM)",
    "Height (CM)": "高度 (CM)",
    "Ctrl: Enter dimensions manually": "Ctrl: 手动输入尺寸",
    "Create Panel": "创建面板",
    "Reset as Inch": "重置为英寸"
}
